name: esp32-s3 运行port

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/esp32/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_idf50:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: source tools/ci-lin.sh && ci_esp32_idf50_setup
    - name: Build
      run: source tools/ci-lin.sh && ci_esp32_build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: micropython-bin
        path: /home/runner/work/micropython/micropython/ports/esp32/build-ESP32_GENERIC_S3/firmware.bin
